function out1 = f_Qdd2(ap,q1,q2,qd1,qd2,u1,u2)
%F_QDD2
%    OUT1 = F_QDD2(AP,Q1,Q2,QD1,QD2,U1,U2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Mar-2020 09:00:52

t2 = cos(q2);
t3 = sin(q2);
t4 = sin(q1);
t5 = q1+q2;
t6 = sin(t5);
t7 = cos(t5);
t8 = cos(q1);
t9 = qd1.^2;
t10 = qd2.^2;
out1 = ((t4.*2.4740029314e10-t6.*3.909355632e10+u1.*5.1376e7-u2.*3.45776e8+ap.*t7.*3.985072e9+ap.*t8.*1.08509674e10+t2.*t4.*4.206806604e10-t2.*t6.*1.1600587908e10+t3.*t9.*3.978433823e9+t3.*t10.*5.91122623e8+t2.*u1.*8.736e7-t2.*u2.*1.7472e8+ap.*t2.*t7.*1.1825268e9+ap.*t2.*t8.*2.469012e9+qd1.*qd2.*t3.*1.182245246e9+t2.*t3.*t9.*2.01029556e9+t2.*t3.*t10.*1.00514778e9+qd1.*qd2.*t2.*t3.*2.01029556e9).*4.387414555101539e-7)./(t2.^2.*4.41e2-8.74e2);
