function Fy = f_Fy(l,m,q1,q2,qd1,qd2,qdd1,qdd2)
%F_FY
%    FY = F_FY(L,M,Q1,Q2,QD1,QD2,QDD1,QDD2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Mar-2020 11:34:26

t2 = pi./2.0;
t3 = q1+t2;
t4 = qd1+qd2;
t5 = q1+q2+t2;
t6 = qd1.^2;
t7 = sin(t3);
t8 = t6.*t7;
t9 = cos(t3);
t10 = t8-qdd1.*t9;
Fy = m.*(9.81e2./1.0e2)-m.*((l.*t10)./2.0+l.*(t4.^2.*sin(t5)-cos(t5).*(qdd1+qdd2)).*(7.0./4.0e1)).*(1.3e1./2.0e1)-l.*m.*t10.*(7.0./8.0e1);
